---
title: "NYC Inspections Dashboard - American, French, Italian, & Japanese Restaurants"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    source_code: embed 
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(p8105.datasets)
library(plotly)
library(lubridate)
```


```{r}
data("rest_inspec")

rest_inspec = 
  rest_inspec %>% 
  filter(boro == "MANHATTAN", grade != "Not Yet Graded", grade == c("A", "B", "C"), cuisine_description == c("American", "French", "Italian", "Japanese")) %>% 
  mutate(grade = as.factor(grade), grade = fct_relevel(grade, "C", "B", "A"), cuisine_description = as.factor(cuisine_description))
  
```


Column {data-width=550}
-----------------------------------------------------------------------

### Distribution of Health Inspection Scores by Cuisince Type

```{r}
rest_inspec %>% 
  plot_ly(x = ~score, color = ~cuisine_description, type = "box") %>%
  layout(yaxis = list(title = 'Cuisine Type')) %>% 
  layout(xaxis = list(title = 'Health Inspection Score')) %>% 
  layout(showlegend = FALSE)
```

Column {data-width=450}
-----------------------------------------------------------------------

### Number of A, B, and C ratings by Cuisine Type 

```{r}
rest_inspec %>% 
  group_by(cuisine_description, grade) %>% 
  summarize(n_obs = n()) %>% 
  group_by(cuisine_description) %>% 
  mutate(percent = round(100*n_obs/sum(n_obs), 2), text_label = str_c("Grade:", grade, "\nPercent within Cuisine: ", percent, "%")) %>% 
  plot_ly(x = ~cuisine_description, y = ~n_obs, type = "bar", color = ~grade, text = ~text_label) %>%
  layout(yaxis = list(title = 'Count'), barmode = 'stack') %>% 
  layout(xaxis = list(title = 'Cuisine Type'))
```

### Variability of A, B, and C ratings over month of year 

```{r}
rest_inspec %>% 
  mutate(inspection_month = month(inspection_date)) %>% 
  group_by(grade, inspection_month) %>% 
  summarize(n_obs = n()) %>% 
  mutate(n_obs = ifelse(n_obs == "NA", 0, n_obs), text_label = str_c("Grade: ", grade, "\nNumber of Resraurants: ", n_obs)) %>% 
  plot_ly(x = ~inspection_month, y = ~n_obs, color = ~grade, type = "scatter", mode = "lines", text = ~text_label) %>%
  layout(yaxis = list(title = 'Number of Italian, French, American, and Japanese Restaurants')) %>% 
  layout(xaxis = list(title = 'Inspection Month'))
```

